src/VueDatePicker/components/DatepickerInput.vue
Hello,
I noticed a weird behavior on the clear icon when using it with a custom slot.
The clear icon is still displayed when there are no value set.
=> Fix clear icon is displayed when clear-icon slot is added

package.json
I have a project that uses this datepicker. I'm creating an SSR build of the project using Vite. When trying to run the resulting bundle using `node`, a `Cannot use import statement outside a module` error happens. Vite correctly imports the `vue-datepicker.es.js` file, but then incorrectly treats it as a CommonJS module. This happens because Vite seems to only treat modules as ES modules if the `package.json` specifies the `type` as `module`.
If I manually edit the `package.json` in my `node_modules` folder to include `"type": "module"`, everything works as expected.
=> Add `"type": "module"` to package.json for Vite resolution

src/VueDatePicker/components/MonthYearPicker/ActionIcon.vue, src/VueDatePicker/components/MonthYearPicker/MonthYearPicker.vue
To fix [DatePick issue.](https://github.com/Vuepic/vue-datepicker/issues/132)
To fix a minor issues with Prev/Next buttons
1. Screenreader announces ActionIcon as "group" instead of "button".
2. Next Month ActionIcon aria label prop typo
=> fix: ActionIcon accessibility issues

src/VueDatePicker/components/DatepickerMenu.vue, src/VueDatePicker/components/MonthYearPicker/MonthYearPicker.vue, src/VueDatePicker/components/MonthYearPicker/RegularPicker.vue, src/VueDatePicker/components/SelectionGrid.vue, src/VueDatePicker/components/TimePicker/TimeInput.vue, src/VueDatePicker/components/TimePicker/TimePicker.vue, tests/unit/logic.spec.ts
For [issue 139](https://github.com/Vuepic/vue-datepicker/issues/139).
Affected: month/year/hour/minute overlay
1. When DatePicker is in dropdown mode: same behavior as before
-escClose=true, keypress Esc will close overlay if any is showing. It also closes date picker menu.
-escClose=false, Esc does nothing 
2. When in inline mode:
-escClose=true, Esc will close month/year/hour/minute overlay (new behavior)
-escClose=false, Esc does nothing
=> feat: support keyboard Esc to close month/year, or hour/minute overlay depending on prop escClose

index.d.ts
When extending vue-datepicker with custom implementations, importing interfaces individually (as opposed to the `_default` export typed as `DefineComponent`) helps keep typing in-sync.
=> refactor(type definition): export interfaces in declaration file

src/VueDatePicker/components/Calendar.vue
helps to style the tooltips of markers by using `html` parameter instead of `text` when adding markers
e.g. 
```js
const markers = ref([
{
date: new Date(),
type: 'line',
tooltip: [
{ html: 'First tooltip <br> <b>fff</b>', color: 'blue' },
{ text: 'Second tooltip', color: 'yellow' },
],
}
])
```
**potential issue:** depending on where the data  for the markers comes from, opens the code up for code injection.
=> add html as optional parameter to calendar marker's tooltips

src/VueDatePicker/components/Calendar.vue, src/VueDatePicker/interfaces.ts, src/VueDatePicker/utils/util.ts
**Why**
-When navigating inside calendar datagrid, screenreader will announce day cell content, which is a number by default. For screenreader user, we may need to customize day cell text content to announce more info like weekday, or full date (Month-day-year). 
**Existing implementation**
-Tried slots "day" with aria-label to override inner text content. It works with VoiceOver (mac/iOS), but does not work with  NVDA (windows) default browse mode. 
**Solution**
Extending props ariaLabels by adding an optional "day" function to allow customization. 
Tested VoiceOver and NVDA.
Sample code:
Generated DOM:
**Question**
If this PR is accepted, I'd like to know how to update documentations. I can see they're under docs/api folder. @Jasenkoo
=> [Accessibility] Allow aria-label customization for day cell in Calendar component

src/VueDatePicker/utils/date-utils.ts
When using UTC preserve instead of doing timezone calculations in milliseconds, simply take the fields from the date itself and return a UTC formatted string with those values.
=> UTC preserve timezone calculation fix

src/VueDatePicker/components/DatepickerMenu.vue
There is no `resize` event on `document` object.
Reference: https://stackoverflow.com/questions/12045440/difference-between-document-addeventlistener-and-window-addeventlistener
=> fix: addEventListener

src/VueDatePicker/components/composables/calendar.ts
If you change the month manually (via the arrows or selection) the 'update-month-year' it is emitted.
When scrolling the mouse wheel over the calendar, the month will change but the 'update-month-year' event is not emitted.
=> fix: emit update-month-year event when scrolling over the calendar.

src/VueDatePicker/style/_variables.scss
Add an option to configure the border-radius with a custom property without the need to rebuild the sass file. Usage:
```css
.dp__main {
--border-radius: 0; /* Disable border radius */
}
```
=> Configurable border radius

src/VueDatePicker/style/components/_ActionRow.scss, src/VueDatePicker/style/main.scss
Remove redundant background colors. Background color is already applied to `.dp__menu`. Removing the background from `.dp__action_row` also resolves the overflow issue which is caused by the border radius:
=> Remove redundant backgrounds

src/VueDatePicker/style/main.scss
This will fix position of `now` button in month/year view when teleport-center is active.
=> Fix position of now button - fix #353

src/VueDatePicker/style/components/_ActionRow.scss, src/VueDatePicker/style/main.scss
Closes #361 
Use `flex-start` or `flex-end` as the value of `justify-content` and `align-items` to prevent mixed support on the browser. Especially for **Nuxt** because the bundler configuration for CSS has a strict rule (which is good for us).
=> Fix flexbox value with mixed support

src/VueDatePicker/components/composables/utils.ts, src/VueDatePicker/interfaces.ts, src/VueDatePicker/utils/props.ts, tests/unit/utils.spec.ts
As said in #370, this allows to configure whether additional weeks should be appended (default, old implementation) or prepended, or distributed depending on which weekday the month starts.
=> feat: Allow configuration of six-week mode offset padding

package.json
This fixes the following error using TS 5:
```bash
error TS7016: Could not find a declaration file for module '@vuepic/vue-datepicker'. 'node_modules/.pnpm/@vuepic+vue-datepicker@5.0.0_vue@3.2.47/node_modules/@vuepic/vue-datepicker/dist/vue-datepicker.js' implicitly has an 'any' type.
There are types at 'node_modules/@vuepic/vue-datepicker/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vuepic/vue-datepicker' library may need to update its package.json or typings.
```
=> Export library types

index.d.ts
VueDatepicker has the typescript error when i try to passing property 'menuAppear' in transitions prop.
I suggest a small fix. Please see my PR.
=> Fix VueDatePickerProps interface transitions prop

src/VueDatePicker/VueDatePicker.vue, src/VueDatePicker/components/ActionRow.vue, src/VueDatePicker/components/Calendar.vue, src/VueDatePicker/components/DatepickerInput.vue, src/VueDatePicker/components/DatepickerMenu.vue, src/VueDatePicker/components/Icons/CalendarIcon.ts, src/VueDatePicker/components/Icons/CancelIcon.ts, src/VueDatePicker/components/Icons/ChevronDownIcon.ts, src/VueDatePicker/components/Icons/ChevronLeftIcon.ts, src/VueDatePicker/components/Icons/ChevronRightIcon.ts, src/VueDatePicker/components/Icons/ChevronUpIcon.ts, src/VueDatePicker/components/Icons/ClockIcon.ts, src/VueDatePicker/components/MonthYearPicker/ActionIcon.vue, src/VueDatePicker/components/MonthYearPicker/MonthYearPicker.vue, src/VueDatePicker/components/MonthYearPicker/RegularPicker.vue, src/VueDatePicker/components/SelectionGrid.vue, src/VueDatePicker/components/TimePicker/TimeInput.vue, src/VueDatePicker/components/TimePicker/TimePicker.vue
I didn't get app compatible with Vue 2.
But for app in Vue 3 with @vue/compat dependancy some configuration is needed.
I add this configuration for all component and now the datepicker is working nicely.
=> feat(global): Adding configuration to support app using @vue/compat

src/VueDatePicker/style/components/_ActionRow.scss, src/VueDatePicker/style/components/_Calendar.scss, src/VueDatePicker/style/components/_DatepickerInput.scss, src/VueDatePicker/style/components/_DatepickerMenu.scss, src/VueDatePicker/style/components/_MonthYearInput.scss, src/VueDatePicker/style/components/_SelectionGrid.scss
❤️ Thank you @Jasenkoo  for this wonderful package.
This PR introduces support for RTL languages.
Before : 
After: 
----- 
I'm wondering why Markdown is not available to edit documents. I need to add an example for `RTL` in `customization.
```vue
<template>
<div class="wrapper" dir="rtl">
<Datepicker
placeholder="اختر التاريخ"
v-model="date"
range
multi-calendars
locale="ar"
now-button-label="Current"
:day-names="['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت']"
:preset-ranges="presetRanges"
teleport
select-text="موافق"
cancel-text="إلغاء"
:allow-prevent-default="true"
:enable-time-picker="false"
/>
</div>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import Datepicker from '../src/VueDatePicker/VueDatePicker.vue';
const date = ref();
const today …
```
=> feat(style): support RTL 

src/VueDatePicker/components/DatepickerMenu.vue, src/VueDatePicker/style/components/_DatepickerMenu.scss
**Why this PR?**
In a current project we are using the vue-datepicker because it works very well accessibility-wise. While testing, we discovered that it's **not possible to use the tab navigation to access the configured "preset-ranges"** in the sidebar using the keyboard's tab keys.
**Content of this PR**
This PR contains the updated implementation and the updated documentation for the "preset-ranges". The Documentation can be found in this PR description. (See section "Documentation update")
- Streamlined the syntax of the slot written by the user and the syntax of the default implementation in src/VueDatePicker/components/DatepickerMenu.vue. They now share the same syntax.
- Added arial role button
- Added tabindex
- It's now possible to select a range by "click", but also "enter" or …
=> preset-ranges: Keyboard navigation (tabindex, aria button) + steamlined slot template

src/VueDatePicker/VueDatePicker.vue, src/VueDatePicker/components/DatepickerInput.vue, src/VueDatePicker/interfaces.ts
Fixed the bugs listed below.
1. auto-apply and text-input
2. input DateTime
3. click clear button
4. focus input and open Menu（no input）
5. click outside and close Menu
6. prev inputed DateTime is set
replication：[https://stackblitz.com/edit/nuxt-starter-tdp8cr?file=app.vue](https://stackblitz.com/edit/nuxt-starter-tdp8cr?file=app.vue
)
=> fix: prev val is set when auto-apply & text-input

index.d.ts
Sometimes we need to reset internalModelValue by setting it to `null` in `updateInternalModelValue` public method. This PR fixes incoming parameter type.
=> fix: Add null type to updateInternalModelValue parameter types

src/VueDatePicker/components/DatePicker/DpCalendar.vue
The calendar currently has nested grid role, this causes an [aria-required-children](https://accessibilityinsights.io/info-examples/web/aria-required-children/) error. I have replaced the nested `grid` with a `rowgroup`.
=> fix: Incorrect aria role

src/VueDatePicker/components/DatePicker/DpCalendar.vue, src/VueDatePicker/components/DatePicker/date-picker.ts, src/VueDatePicker/components/MonthPicker/month-picker.ts, src/VueDatePicker/components/QuarterPicker/quarter-picker.ts, src/VueDatePicker/components/TimePicker/TimeInput.vue, src/VueDatePicker/components/TimePicker/time-picker-utils.ts, src/VueDatePicker/components/TimePicker/time-picker.ts, src/VueDatePicker/components/YearPicker/year-picker.ts, src/VueDatePicker/components/shared/month-quarter-picker.ts, src/VueDatePicker/composables/calendar-class.ts, src/VueDatePicker/composables/external-internal-mapper.ts, src/VueDatePicker/composables/model.ts, src/VueDatePicker/composables/month-year.ts, src/VueDatePicker/composables/validation.ts, src/VueDatePicker/utils/date-utils.ts, src/VueDatePicker/utils/util.ts
While `date-fns` support [tree-shaking out-of-the-box](https://date-fns.org/v2.30.0/docs/ECMAScript-Modules), importing from the root of the module (`import { ... } from 'date-fns'`) still require parsing every file of  `date-fns`.
The PR reduce the amount of files parsed
- ES and UMD: **-31** files
- IIFE: **-298** files
It also results into a smaller package
- ES: **-101.42 kB** (-35%) and **16.99 kB** (-27%) compressed
- UMD: **-67.87 kB** (-32%) and **14.49 kB** (-27%) compressed
- IIFE: **-3 kB** (-0.01%) and **0.56 kB** (-1%) compressed
```diff
$ npm run build
> cross-env NODE_ENV=production vite build --mode production
vite v4.4.11 building for production...
-✓ 234 modules transformed.
-dist/vue-datepicker.js  288.53 kB │ gzip: 63.29 kB
-dist/vue-datepicker.umd.cjs  209.02 kB │ …
```
=> Use explicit import for date-fns to improve treeshaking

vite.config.ts
```diff
$ npm run build
...
> cross-env NODE_ENV=production vite build --mode production
vite v4.4.11 building for production...
-✓ 203 modules transformed.
-dist/vue-datepicker.js  187.11 kB │ gzip: 46.30 kB
-dist/vue-datepicker.umd.cjs  141.15 kB │ gzip: 39.67 kB
-✓ built in 1.09s
+✓ 74 modules transformed.
+dist/vue-datepicker.js  176.66 kB │ gzip: 43.28 kB
+dist/vue-datepicker.umd.cjs  134.50 kB │ gzip: 37.37 kB
+✓ built in 854ms
> @vuepic/vue-datepicker@7.2.0 build:browser
> cross-env NODE_ENV=production vite -f iife build --mode production
vite v4.4.11 building for production...
-✓ 532 modules transformed.
-dist/vue-datepicker.iife.js  208.78 kB │ gzip: 53.52 kB
-✓ built in 1.68s
+✓ 234 modules transformed.
+dist/vue-datepicker.iife.js  208.81 kB │ gzip: 54.08 kB
+✓ built in 1.16s
> …
```
=> Update vite config to works with explicit import

src/VueDatePicker/composables/position.ts
When loaded in a web component / custom element, `const container = document.createElement('div');` is created within the shadow DOM, and the statement `document.getElementById('dp--temp-container')` won't return the wished "container" element
closes #656
=> fix(position): fix DatePickerMenu not opening when used inside a webcomponent

src/VueDatePicker/VueDatePicker.vue
I was recently implementing this library in our companies component library, but ran into an issue with transitions and teleport.
To support transitions with teleport, the order of the components had to be swapped, the transition component inside the teleport component.
I also updated the prop behaviour so the teleport doesn't need conditional rendering and is just disabled when there is no teleport enabled.
The menu is now just a div always the ```dp__outer_menu_wrap``` class since it no longer renders as a teleport in some cases.
=> fix: Updated VueDatePicker teleport implementation to support menuAppear transitions

src/VueDatePicker/components/DatePicker/date-picker.ts
This is an improved implementation of the issue that was resolved here: https://github.com/Vuepic/vue-datepicker/issues/671
The original debounce approach does inhibit uncontrollable scrolling through months, but it also makes the calendar feel extremely sluggish when using a Mac touchpad, as it must wait until the scrolling has completely finished/resolved before the month will change. Rather than using a debounce, throttling the scroll behavior provides a much more responsive experience. 
A flat rate throttle of 1 effective scroll/month change every 100ms provides a good overall experience. But it can be still be touchy for small changes, and also feel slightly sluggish when scrolling rapidly. This implementation includes a variable rate throttle to ensure more control and precision …
=> Changed debounce on month-change-on-scroll to a variable rate throttle

src/VueDatePicker/composables/external-internal-mapper.ts
I found if I use P as format and model-type and fr as format-locale then when I select a date then the month and day switch each other.
That's because day and month aren't in the same order in french and in english.
=> fix(ExternalInternalMapper): Take format-locale as locale when parsing date

src/VueDatePicker/props.ts
This pull request addresses an issue with the `teleport` prop where it was not working correctly when passed as a boolean attribute without a value (e.g., `<Datepicker teleport />`).
This behavior was caused by the boolean casting rules in Vue 3, as described in the documentation: https://vuejs.org/guide/components/props.html#boolean-casting
By moving `Boolean` before `String` in the type array, the boolean casting rules are applied correctly, allowing the `teleport` prop to work as expected when used as a boolean attribute.
```js
teleport: { type: [Boolean, String, Object] as PropType<boolean | string | HTMLElement>, default: null },
```
=> fix: change teleport prop type order to fix boolean casting

src/VueDatePicker/components/DatePicker/DatePicker.vue, src/VueDatePicker/components/DatePicker/date-picker.ts
Answering to this proposal:
Refs: #885
=> feat(date-picker): Add calendar instance when count sub-property is incremented from external context

src/VueDatePicker/components/DatepickerMenu.vue
This pull request addresses an issue with the `arrowPos` calculation that throws a null reference error if the `inputRect` is undefined. This can happen when using the `inline` mode of the date picker. 
I can't reproduce this in an isolated environment (e.g. jsfiddle) but it happens every time in our project. We've added a temporary work around with `:config="{ arrowLeft: '0px' }"`.
Ideally, this computed calculation should not even need to run when in `inline` mode, but safe navigating inside it is also a viable solution to handle this issue.
=> fix: Add safe navigation to arrow position calculation

src/VueDatePicker/utils/util.ts, tests/unit/utils.spec.ts
The same issue we have in https://github.com/Vuepic/vue-datepicker/issues/817, but with days names.
In negative timezones, we faced the shift in days. Saturday became the first day of the week.
I've added small fix. And also implement some new tests.
I also have an alternative solution without using date-fns `format` function at all. Will post it bellow, and maybe we can switch to it, because of optimization effort.
=> fix: Wrong weekday names when using `format-locale` in overridden timezone

src/VueDatePicker/components/DatepickerMenu.vue
this is a fix for issue https://github.com/Vuepic/vue-datepicker/issues/920
the popup arrow is not pointing to the center of the field, when the field is on the right most of the area and there is not enough screen width to center the popup. This issue seems solved only when it is on the left via issue https://github.com/Vuepic/vue-datepicker/issues/802.
I added check for the right side. if there is not enough width, then position arrow to middle of input.
done, no issue locally. but pull request showing one failed test.  
npm run test:coverage and npm run test works fine locally
and it works for other situations, left and default
=> fix: Arrow not positioned correctly when the field at the most right

src/VueDatePicker/components/DatePicker/date-picker.ts
This PR solves #909, in which the second calendar appears with the wrong year and month when simultaneously using auto-range and multi-calendar features.
Upon investigation, I found that the year and month values were mistakenly assigned interchangeably in the `handleNextCalendarAutoRange` function, leading to the bug.
After fixing it, I confirmed that the second calendar showed the correct year and month.
=> fix: Wrong month & year assignment for auto-range multi calendars

src/VueDatePicker/components/DatepickerInput.vue
Because the old class, `dp__clear_icon`, was still applied to the parent element of the clear button slot, the clear button was misplaced in the field.
This PR fixes the class so the button is positioned correctly.
Here are the results:
<details>
<summary>The code</summary>
```vue
<template>
<div class="wrapper">
<Datepicker v-model="selectedDate" placeholder="Select Date" clearable>
<template #clear-icon="{ clear }">
<div class="clear" @click="clear">⭐</div>
</template>
</Datepicker>
</div>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
import Datepicker from '../src/VueDatePicker/VueDatePicker.vue';
const selectedDate = ref();
</script>
<style lang="scss">
@import 'src/VueDatePicker/style/main';
.wrapper {
padding: 200px;
}
.clear {
margin: 4px 8px;
}
</style>
``` …
=> fix: Wrong class for the clear button slot

src/VueDatePicker/components/DatepickerInput.vue
Fixes 2 bugs that occurs when pressing TAB while using `text-input` mode:
Fix: The value is now fetched directly from the `inputRef` in `handleTab`. This is because the previous code would get the value from `ev.target` which will be the clear-button (`<button>`) when TAB'ing.
I would expect the string to be parsed as soon as i pressed TAB, even though the focus shifts to the clear-button. I have therefore updated the `handleTab` to do that.
Fixes #961
=> fix: bugs with tab-handling in `text-input` mode

src/VueDatePicker/components/DatepickerInput.vue
Disables root level click event if a custom input is provided in dp-input.  There's really no need for it if the input is being customized and it blocks some click events at that input level.
#973
=> fix: root-click not needed with input slot (fixes #973)

src/VueDatePicker/composables/shared.ts
I changed how events are triggered, because when end of range date selected is sooner than start of range date, it triggers range-start twice.
So now, i mantain the unshift in the array to have dates in proper order, but triggering range-end event since range selection is finished.
Fixes #1005
=> Month range picker doesn't trigger rangeStart rangeEnd events properly

package.json, src/VueDatePicker/components/DatepickerMenu.vue, src/VueDatePicker/interfaces.ts, tests/unit/components/Datepicker.spec.ts
Update DatepickerMenu to allow the function presetDate to recibe a `MaybeRefOrGetter<Date[] | string[] | string | Date>` from `PresetDate`.
Update the `PresetDate` interface present in interfaces.ts, to use type MaybeRefOrGetter from vue
Update `package.json`, set peerDependencies to the minimun required vue 3.3.0 (required by MaybeRefOrGetter)
Add 2 new tests, fixed 1:
- `Should preset range from preset-dates` now click on the preset instead of calling its internal function `presetDate`
- add new test `Should preset range from preset-dates when range its a function`, check when value is a function, it should behave same as before
- add new test `Should correctly set today when preset-dates its a function and selected 2 days later`, check that presetDate is executed when pressed, in this …
=> feat: Allow presetDates values to be functions

src/VueDatePicker/components/DatepickerInput.vue, src/VueDatePicker/props.ts
I have added a prop which makes the `clear-icon` slot present regardless of the state of the DatepickerInput
It might help developers who have created their own logic for the clear button
=> feat: alwaysClearable prop

src/VueDatePicker/components/DatePicker/DpHeader.vue
Exposed `isDisabled` method to `#month-year` slot so prev/next button could be custom styled based on the disabled state
https://github.com/Vuepic/vue-datepicker/issues/1056
=> feat: expose isDisabled method to month-year slot

src/VueDatePicker/components/DatepickerInput.vue
Date-fns v4.1.0 treats `null` as `01/01/1970` [(reference)](https://github.com/date-fns/date-fns/issues/3946), which changes the behavior compared to previous versions. To maintain the same behavior as before, we can pass `undefined` instead of `null`. In this change, `null` is replaced with `undefined` while initializing `parsedDateTwo`.
Fixes #1082
=> fix: allow dates after 1970 in range mode

src/VueDatePicker/utils/util.ts, tests/unit/utils.spec.ts
When using `ar` as locale, week days' short names were identical because we would always `slice` the full day names on indexes 0 to 2 to format them. 
I made an exception for arabic, slicing the weekdays on indexes 2 to 5
This is how it looks like now:
| Before | After |
| ------- | --------|
|  <img width="268" alt="image" src="https://github.com/user-attachments/assets/f38e9bdb-e3f9-4b25-9654-7e51a43bb6d4" /> | <img width="264" alt="image" src="https://github.com/user-attachments/assets/06ae99e2-4463-4887-bed1-ba032427598c" />|
Fixes #1087
=> fix: handle arabic short week days

src/VueDatePicker/VueDatePicker.vue, src/VueDatePicker/composables/position.ts
When using slots like this example:
```vue
<script setup>
import { Select } from 'primevue'
import VueDatePicker from '@vuepic/vue-datepicker'
import '@vuepic/vue-datepicker/dist/main.css'
const date = ref()
</script>
<template>
<VueDatePicker v-model="date">
<template #left-sidebar>
<Select />
</template>
</VueDatePicker>
</template>
```
The `<Select>` component would not get passed the appContext while shadow rendering which causes errors, especially on libraries like PrimeVue which require the appContext to use config properties.
Setting appContext after calling h() is what is described by Evan You: https://github.com/vuejs/core/issues/2097#issuecomment-707975628
https://github.com/Vuepic/vue-datepicker/issues/1092
=> fix: App Context missing in slots

src/VueDatePicker/components/DatePicker/DpCalendar.vue, src/VueDatePicker/components/DatepickerMenu.vue
Resolve memory leaks by removing event listeners on component unmount 
- Remove `touch` and `wheel` event listeners in `DpCalendar` component
- Remove `mousedown` and `pointerdown` event listeners in `DatepickerMenu` component
This fix reduces retained size to 0%.
Even with the fix, there is still increase in retained size (as some elements are retained by transition). However, it still has less memory consumption compared to the situation without the fix.
Fixes #1083
=> fix: resolve memory leaks by detached elements and event listeners

src/VueDatePicker/components/DatePicker/DpCalendar.vue
Updates the accessibility attributes for element with `gridcell` role as per [wai-aria gridcell](https://www.w3.org/TR/wai-aria-1.1/#gridcell)
Fixes #1090
=> fix(a11y): replace :aria-pressed with :aria-selected for gridcell role

package.json, src/VueDatePicker/components/Common/ArrowBtn.vue
While working on #1109 I noticed that when running the dev script, it displays the following warning in console:
**_The condition "types" here will never be used as it comes after both "import" and "require" [package.json]_**
- Update package.json, move `exports.".".types` to the top of the list
- Run lint script, changes `ArrowBtn.vue` adds missing `.value` to ref `elRef`
=> fix: vite warning in console
